language: r

r:
  - release
  - devel
  - oldrel

sudo: required
dist: trusty
cache: packages
latex: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libnetcdf-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - netcdf-bin

before_install:
  - R -q -e 'install.packages("remotes"); remotes::install_github("pat-s/tic@rcmdcheck-build-args"); tic::prepare_all_stages(); tic::before_install()'
  # install postgis from source (required for lwgeom installation):
  - wget http://download.osgeo.org/postgis/source/postgis-2.4.4.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.4.4.tar.gz)
  - (cd /tmp/postgis-2.4.4 ; ./configure; make; sudo make install)
after_success: R -q -e 'tic::after_success()'
install: R -q -e 'tic::install()'
script: R -q -e 'tic::script()'

before_deploy: R -q -e 'tic::before_deploy()'
deploy:
   provider: script
   script: R -q -e 'tic::deploy()'
   on:
     branch: master
     condition:
       - $TRAVIS_PULL_REQUEST = false
       - $TRAVIS_EVENT_TYPE != cron
       - $TRAVIS_R_VERSION_STRING = release
