language: r

r:
  - release
  - devel
# - oldrel

sudo: required
dist: trusty
cache:
  - packages
  - ccache
latex: false

r_github_packages:
  - r-spatial/sf

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libnetcdf-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - netcdf-bin

before_install:
  - R -q -e 'install.packages("devtools"); devtools::install_github("ropenscilabs/tic"); install.packages(c("abind", "ncdf4", "ncmeta")); tic::prepare_all_stages()'

after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'

#install: R -q -e 'tic::install()'
#script: R -q -e 'tic::script()'
#before_deploy: R -q -e 'tic::before_deploy()'
#deploy:
#   provider: script
#   script: R -q -e 'tic::deploy()'
#   on:
#     branch: master
#     condition:
#       - $TRAVIS_PULL_REQUEST = false
#       - $TRAVIS_EVENT_TYPE != cron
#       - $TRAVIS_R_VERSION_STRING = release
